-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 08:23:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_professor` (
  `id_usuario_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `instituicao` VARCHAR(255) NULL,
  `registro` INT NULL,
  UNIQUE INDEX (`id_usuario_professor` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario_professor`));


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(255) NULL,
  `data_criacao` DATE NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  UNIQUE INDEX (`id_comentario` ASC) VISIBLE,
  PRIMARY KEY (`id_comentario`, `id_usuario`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario_professor` (`id_usuario_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefa` (
  `id_tarefa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `status` VARCHAR(255) NULL,
  `data_conclusao` DATE NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `id_comentario` INT NOT NULL,
  `id_arquivo` INT NOT NULL,
  UNIQUE INDEX (`id_tarefa` ASC) VISIBLE,
  PRIMARY KEY (`id_tarefa`, `id_comentario`, `id_arquivo`),
  INDEX `id_cometario_idx` (`id_comentario` ASC) VISIBLE,
  CONSTRAINT `id_cometario`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `mydb`.`comentario` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`quadro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quadro` (
  `id_quadro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `data_criacao` DATE NULL,
  `id_tarefa` INT NOT NULL,
  UNIQUE INDEX (`id_quadro` ASC) VISIBLE,
  PRIMARY KEY (`id_quadro`, `id_tarefa`),
  INDEX `id_tarefa_idx` (`id_tarefa` ASC) VISIBLE,
  CONSTRAINT `id_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `mydb`.`tarefa` (`id_tarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projeto` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `progresso` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` DATE NULL,
  `id_quadro` INT NOT NULL,
  UNIQUE INDEX (`id_projeto` ASC) VISIBLE,
  PRIMARY KEY (`id_projeto`, `id_quadro`),
  INDEX `id_quadro_idx` (`id_quadro` ASC) VISIBLE,
  CONSTRAINT `id_quadro`
    FOREIGN KEY (`id_quadro`)
    REFERENCES `mydb`.`quadro` (`id_quadro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificacoes` (
  `id_notificacoes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `texto` VARCHAR(255) NULL,
  `data_publi` DATE NULL,
  PRIMARY KEY (`id_notificacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `data_criacao` DATE NULL,
  `id_projeto` INT NOT NULL,
  `id_notificacoes` INT NOT NULL,
  `id_usuario_professor` INT NOT NULL,
  UNIQUE INDEX (`id_grupo` ASC) VISIBLE,
  PRIMARY KEY (`id_grupo`, `id_projeto`, `id_notificacoes`, `id_usuario_professor`),
  INDEX `teams_index_0` (`id_grupo` ASC) VISIBLE,
  INDEX `id_projeto_idx` (`id_projeto` ASC) VISIBLE,
  INDEX `id_notificacoes_idx` (`id_notificacoes` ASC) VISIBLE,
  INDEX `id_usuario_professor_idx` (`id_usuario_professor` ASC) VISIBLE,
  CONSTRAINT `id_projeto`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `mydb`.`projeto` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_notificacoes`
    FOREIGN KEY (`id_notificacoes`)
    REFERENCES `mydb`.`notificacoes` (`id_notificacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario_professor`
    FOREIGN KEY (`id_usuario_professor`)
    REFERENCES `mydb`.`usuario_professor` (`id_usuario_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `rm` INT NULL,
  `instituicao` VARCHAR(255) NULL,
  `id_grupo` INT NOT NULL,
  UNIQUE INDEX (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`, `id_grupo`),
  INDEX `id_grupo_idx` (`id_grupo` ASC) INVISIBLE,
  CONSTRAINT `id_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
